# Generated by Django 5.1.5 on 2025-04-17 01:47

import ccscms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', ccscms.models.AccountManager()),
            ],
        ),
    ]
