# Generated by Django 5.1.5 on 2025-04-18 02:00

import ccscms.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ccscms', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officermember',
            options={'ordering': ['officer', 'position', 'lastname']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='officer',
            name='officer_supervi_92b2e1_idx',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='accomplishmentimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='images',
        ),
        migrations.RemoveField(
            model_name='achievementimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='audiences',
        ),
        migrations.RemoveField(
            model_name='announcementaudience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='audiences',
        ),
        migrations.RemoveField(
            model_name='event',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='event',
            name='types',
        ),
        migrations.RemoveField(
            model_name='eventaudience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventlabellist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventtypelist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='account',
        ),
        migrations.RemoveField(
            model_name='gallerypostimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='position',
            name='hierarchy_level',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='volunteerannouncement',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='volunteerannouncement',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='volunteerannouncement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='volunteerevent',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accomplishmentimage',
            name='accomplishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ccscms.accomplishment'),
        ),
        migrations.AlterField(
            model_name='achievementimage',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ccscms.achievement'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('students', 'Students'), ('teachers', 'Teachers'), ('faculties', 'Faculties')], max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('research', 'Research'), ('academics', 'Academics'), ('achievements', 'Achievements'), ('special', 'Special'), ('theaters', 'Theaters'), ('parties', 'Parties'), ('drinks', 'Drinks'), ('food', 'Food')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlabel',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='COR_img',
            field=models.ImageField(blank=True, null=True, upload_to=ccscms.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Student number must be numeric with optional dashes', regex='^[0-9-]{8,20}$')]),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_online'], name='account_is_onli_eb5515_idx'),
        ),
    ]
