# Generated by Django 5.1.5 on 2025-05-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0004_passwordreset_visitorlog_remove_event_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='achievement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='awarded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='awarded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
