# Generated by Django 5.1.5 on 2025-05-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0005_remove_achievement_is_active_achievement_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='achievement',
            name='achievement_officer_10448a_idx',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='officer',
        ),
    ]
