# Generated by Django 5.1.5 on 2025-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0006_remove_achievement_achievement_officer_10448a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
