# Generated by Django 5.1.5 on 2025-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0007_achievement_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accomplishment',
            name='accomplishm_officer_e85cc1_idx',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='officer',
        ),
    ]
