# Generated by Django 5.1.5 on 2025-05-12 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0008_remove_accomplishment_accomplishm_officer_e85cc1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Student number must be numeric with optional dashes', regex='^[0-9-]{8,20}$')]),
        ),
    ]
