# Generated by Django 5.1.5 on 2025-05-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0009_alter_user_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_post',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_post',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
