# Generated by Django 5.1.5 on 2025-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0010_announcement_date_post_announcement_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scope',
            field=models.CharField(blank=True, db_column='scope', editable=False, max_length=20, null=True),
        ),
    ]
