# Generated by Django 5.1.5 on 2025-05-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0011_category_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='scope',
            field=models.ForeignKey(blank=True, db_column='scope_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ccscms.scope'),
        ),
    ]
