# Generated by Django 5.1.5 on 2025-05-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0014_feedbacktype_feedback_feedback_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='other_info',
        ),
    ]
