# Generated by Django 5.1.5 on 2025-05-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0015_remove_complaint_other_info'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accomplishment',
            name='accomplishm_status__c7a68c_idx',
        ),
        migrations.RemoveField(
            model_name='accomplishment',
            name='status',
        ),
    ]
