# Generated by Django 5.1.5 on 2025-05-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0016_remove_accomplishment_accomplishm_status__c7a68c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='achievement',
            name='achievement_status__49607e_idx',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='status',
        ),
    ]
