# Generated by Django 5.1.5 on 2025-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0017_remove_achievement_achievement_status__49607e_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='mentor',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='achievement',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
