# Generated by Django 5.1.5 on 2025-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0019_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transparency',
            name='document_url',
        ),
        migrations.AddField(
            model_name='transparency',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='transparency_docs/'),
        ),
    ]
