# Generated by Django 5.1.5 on 2025-05-22 10:26

import ccscms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0022_positiontype_position_position_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='officermember',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=ccscms.models.upload_to),
        ),
    ]
