# Generated by Django 5.1.5 on 2025-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0023_officermember_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
