# Generated by Django 5.1.5 on 2025-06-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccscms', '0024_alter_committeemember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'committee_role',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['committee', 'role__name', 'lastname']},
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='ccscms.committeerole'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['role'], name='committee_m_role_id_ec8306_idx'),
        ),
    ]
